name: Metrics
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrci1 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics1.svg
          user: lavitalite
          base: header, activity, repositories, metadata
          config_timezone: Asia/Chongqing
          config_twemoji: yes
          repositories_skipped: node_farm
          use_prebuilt_image: yes


          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          
      - name: Metrics2 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics2.svg
          user: lavitalite
          base: ""
          config_timezone: Asia/Chongqing
          config_twemoji: yes
          repositories_skipped: node_farm
          use_prebuilt_image: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_havits_days: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: deployer, gister,automator

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
        
    
