name: Metrics
on: 
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  USER_NAME: lavitalite

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: production
    env: 
      TEST: print built-in secrets
    steps:
      - name: ${{env.TEST}}
        run: |
          echo "$PRINT_ENV_SECRET ${{secrets.METRICS_TOKEN}}"
          echo "$PRINT_REPO_SECRET ${{vars}}"
        env: 
          PRINT_ENV_SECRET: env secrets pipline ->
          PRINT_REPO_SECRET: repo secrets pipline ->
      - name: Metrics1 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics1.svg
          user: ${{ env.USER_NAME }}
          base: header
          config_timezone: Asia/Chongqing
          config_twemoji: yes
          use_prebuilt_image: yes
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_ignored: html, css 
          plugin_languages_limit: 4

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          
      - name: Metrics2 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics2.svg
          user: ${{ env.USER_NAME }}
          base: ""
          config_timezone: Asia/Chongqing
          config_twemoji: yes
          repositories_skipped: node_farm
          use_prebuilt_image: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: deployer, gister,automator


        
    
